import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Noto_Sans_Bengali } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });
const bengali = Noto_Sans_Bengali({subsets: ["bengali"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bengali.className} bg-gray-100`}>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
